# Proxima docker-compose.yaml v2.0.1
# authors:
#  - NotAShelf <me@notashelf.dev> 
#  - XCraftMan52 <lucas@lucaswebber.net>

services:
  proxima:
    tty: true
    working_dir: /opt/proxima
    build: .
    #image: proxima/proxima:latest
    command: pnpm start
    container_name: Proxima
    restart: unless-stopped
    volumes:
      - ./data:/opt/proxima/data
      - ./src:/opt/proxima/src
    environment: []
