# BrayanBot docker-compose.yaml v2.0.0
# authors:
#  - NotAShelf <me@notashelf.dev> 
#  - XCraftMan52 <lucas@lucaswebber.net>

services:
  brayanbot:
    tty: true
    working_dir: /opt/brayanbot
    build: .
    command: pnpm start
    container_name: BrayanBot
    restart: unless-stopped
    volumes:
      - ./data:/opt/brayanbot/data
      - ./src:/opt/brayanbot/src
    environment:
      - LOG_LEVEL=debug # debug, info, warn, error
      - FORCE_COLOR=3 # force color output
