# BryanBot docker-compose.yaml v2.0.2
# authors:
#  - NotAShelf <raf@notashelf.dev>
#  - XCraftMan52 <lucas@lucaswebber.net>

services:
  bryanbot:
    tty: true
    working_dir: /opt/bryanbot
    image: Neushore/BrayanBot:latest
    command: pnpm start
    container_name: BryanBot
    restart: unless-stopped
    volumes:
      - ./data:/opt/bryanbot/data
      - ./src:/opt/bryanbot/src
    environment: []
