name: Docker Image CI

on:
  push:
    tags:
    - v*
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  build:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v1
      with:
        platforms: all

      # Set-up Docker Buildx Plugin
    - name: Set up Docker Buildx
      id: buildx
      uses: docker/setup-buildx-action@v1
      with:
        version: latest

      # Logs into Docker using the credientals from the repository secrets
    - name: Login to DockerHub
      if: ${{ github.actor == github.repository_owner }}
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

      # It's about time we pushed the images, eh?
    - name: Build and push the Docker images
      run: |
        BRANCH_NAME="${GITHUB_REF#refs/heads/}"
        if [[ "${GITHUB_REF}" =~ ^refs\/pull\/.*$ ]]; then
          BRANCH_NAME="${GITHUB_HEAD_REF#refs/heads/}"
        fi
        if [[ "${BRANCH_NAME}" == *"/"* ]]; then
          BRANCH_NAME="${BRANCH_NAME//\//-}"
        fi
        DATE="$(date -u +%Y-%m-%dT%H:%M:%SZ)"
        REF="${BRANCH_NAME:-main}"
        OTHER_TAGS=()
        OTHER_ARGS=""
        OTHER_PUSH_ARGS=""
        if [[ "${GITHUB_ACTOR}" == "${GITHUB_REPOSITORY%/*}" ]]; then
          OTHER_PUSH_ARGS="${OTHER_PUSH_ARGS} --push"
          OTHER_ARGS="${OTHER_ARGS} --platform linux/arm/v7,linux/arm64,linux/amd64 --cache-to type=registry,ref=brayanbot-cache,mode=max"
        else
          OTHER_ARGS="${OTHER_ARGS} --load"
        fi
        if [[ "${GITHUB_REF}" =~ ^refs\/tags\/v.*$ ]]; then
          REF="${GITHUB_REF//refs\/tags\/v}"
          OTHER_TAGS+=("${GITHUB_REF//refs\/tags\/}")
          if ! [[ ${GITHUB_REF} =~ ^refs\/tags\/v.*-.*$ ]]; then
            OTHER_TAGS+=("latest")
          fi
        fi
        if ! docker buildx imagetools inspect brayanbot-build-cache:latest > /dev/null 2>&1; then
          docker pull alpine:latest
          docker tag alpine:latest brayanbot-build-cache:latest
          if [[ "${GITHUB_ACTOR}" == "${GITHUB_REPOSITORY%/*}" ]]; then
            docker push brayanbot-build-cache:latest
          fi
        fi
        OTHER_TAGS+=("${GITHUB_SHA}" "${REF}")
        MAIN_IMAGE_TAGS=""
        BUILD_IMAGE_TAGS=""
        for TAG in ${OTHER_TAGS[@]}; do
          MAIN_IMAGE_TAGS="${MAIN_IMAGE_TAGS} -t brayanbot:${TAG}"
          BUILD_IMAGE_TAGS="${BUILD_IMAGE_TAGS} -t brayanbot-build-image:${TAG}"
        done
        docker buildx build \
          --target release \
          --cache-from brayanbot-cache \
          --build-arg VERSION=${REF} \
          --build-arg COMMIT=${GITHUB_SHA} \
          --build-arg DATE=${DATE} \
          --build-arg REPOSITORY=brayanbot \
          ${MAIN_IMAGE_TAGS} ${OTHER_ARGS} ${OTHER_PUSH_ARGS} .
        if [[ "${OTHER_ARGS}" != *"--load"* ]]; then
          docker buildx build \
            --target release \
            --cache-from brayanbot-cache \
            --build-arg VERSION=${REF} \
            --build-arg COMMIT=${GITHUB_SHA} \
            --build-arg DATE=${DATE} \
            --build-arg REPOSITORY=brayanbot \
            ${MAIN_IMAGE_TAGS} --load .
        fi
        if [[ "${GITHUB_ACTOR}" == "${GITHUB_REPOSITORY%/*}" ]]; then
          docker buildx build \
            --target build-image \
            --cache-from brayanbot-cache \
            --build-arg VERSION=${REF} \
            --build-arg COMMIT=${GITHUB_SHA} \
            --build-arg DATE=${DATE} \
            --build-arg REPOSITORY=brayanbot \
            ${BUILD_IMAGE_TAGS} ${OTHER_ARGS} ${OTHER_PUSH_ARGS} .
        fi
        if [[ "${GITHUB_ACTOR}" == "${GITHUB_REPOSITORY%/*}" ]]; then
          docker buildx build \
            --target build-cache \
            --build-arg VERSION=${REF} \
            --build-arg COMMIT=${GITHUB_SHA} \
            --build-arg DATE=${DATE} \
            --build-arg REPOSITORY=brayanbot \
            -t brayanbot-build-cache:latest \
            ${OTHER_PUSH_ARGS} .
        fi
        docker run --rm brayanbot:${GITHUB_SHA} -v