# We would like to keep our Docker image up to date, but we are lazy. How do we do it? We use Github Actions!
name: Docker Image CI

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x86_64] # more can be added here, if necessary

    steps:
      # Checkout to the git repository
      - name: Checkout
        uses: actions/checkout@v4

      # Logs into Docker using the credientals from the repository secrets
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          nix build .#packages.${{ matrix.arch }}-linux.docker

      - name: Load and preview Docker image
        run: |
          docker load < result &&
          docker images

      - name: Push Docker image
        run: |
          docker tag ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:latest ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:${{ matrix.arch }}-latest
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/${{ secrets.DOCKER_HUB_REPO }}:${{ matrix.arch }}-latest
