name: Dev Branch CI

on:
  push:
    branches: ["dev/*"]

jobs:
  release-dev:
    name: Publish in-dev release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1

      # Set Variables
      - name: Set variables
        id: vars
        run: echo ::set-output name=version::${GITHUB_REF#refs/*\/dev/}

      # Zip up everything excluding Dockerfile and docker-compose.yml
      - name: Archive Source code
        run: zip -r Proxima-v${{ steps.vars.outputs.version }}.zip * -x Dockerfile docker-compose.yml Dockerignore

      # Fetch pterodactyl egg
      - name: Receive Pterodactyl Egg
        run: wget -O pterodacytl-egg.json https://cdn.zorino.in/egg-proxima-bot.json

      # Create a prerelease
      - uses: "marvinpinto/action-automatic-releases@latest"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "${{ steps.vars.outputs.version }}-DEV"
          prerelease: true
          title: "Development Build (${{ steps.vars.outputs.version }})"
          files: |
            Proxima-*.zip
            Dockerfile
            docker-compose.yml
            pterodacytl-egg.json
